export default function TermsPage() {
  const items = [
    {
      title: 'No warranty',
      body: 'This service is provided as-is, without warranty of any kind, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or accuracy of results.',
    },
    {
      title: 'Tax calculations are estimates only',
      body: 'All tax, withholding, and deduction amounts generated by this service — including Auto Tax and any other automated calculations — are estimates based on standard tax tables and the information you provide. They do not account for your complete financial situation, such as additional income, credits, dependents, wage-base caps, year-to-date totals, or local taxes, and may differ from your actual tax liability. SimplePaystub is not a tax preparation service and does not provide tax, legal, accounting, or financial advice. You should verify all figures with your employer’s payroll department, a certified tax professional, or the appropriate tax authority (such as the IRS, CRA, or your state or provincial agency) before relying on any figure for filing, employment, lending, or legal purposes.',
    },
    {
      title: 'Acceptable use',
      body: 'You agree to use this service only for lawful purposes and only to create paystubs that accurately reflect actual income and employment. You may not use this service to create falsified, fraudulent, or misleading documents, or to misrepresent income to any third party, including employers, lenders, landlords, government agencies, courts, or insurers. Creating or using false paystubs may violate federal, state, or provincial law. You are solely responsible for how you use any document generated by this service.',
    },
    {
      title: 'Your responsibility',
      body: 'You are responsible for the accuracy of the information you provide, the correctness of any paystub you generate, and the lawful use of any generated document. You agree to indemnify and hold SimplePaystub harmless from any claims, damages, or liabilities arising from your use of the service.',
    },
    {
      title: 'Limitation of liability',
      body: 'To the fullest extent permitted by law, SimplePaystub and its operators shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use of the service, including but not limited to incorrect tax calculations, missed withholdings, misreported income, tax penalties, interest, or any loss arising from reliance on any document or figure generated by the service. Our total liability for any claim related to the service shall not exceed the amount you paid us, if any, in the twelve months preceding the claim.',
    },
    {
      title: 'Updates to terms',
      body: 'We reserve the right to update these terms at any time. Continued use of the service after an update constitutes acceptance of the revised terms.',
    },
  ];

  return (
    <div className="w-full max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
      <div className="mb-10">
        <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-slate-500">
          Welcome to SimplePaystub.com. By using our service, you agree to the following terms and conditions.
        </p>
      </div>

      <div className="space-y-4">
        {items.map((item, index) => (
          <div key={index} className="bg-white rounded-lg border border-slate-200 p-6">
            <h3 className="text-base font-semibold text-slate-900 mb-2">{item.title}</h3>
            <p className="text-slate-600 leading-relaxed text-sm">{item.body}</p>
          </div>
        ))}
      </div>

      <div className="mt-8 bg-white rounded-lg border border-slate-200 p-6 text-center">
        <h3 className="text-base font-semibold text-slate-900 mb-1">Questions about these terms?</h3>
        <p className="text-slate-500 text-sm">
          Visit our{' '}
          <a href="/help" className="text-primary hover:underline">
            Help Center
          </a>{' '}
          or contact us at{' '}
          <a href="mailto:support@simplepaystub.com" className="text-primary hover:underline">
            support@simplepaystub.com
          </a>
          .
        </p>
      </div>
    </div>
  );
}
