import Link from 'next/link';
import paths from '@/paths';

export default function TermsPage() {
  return (
    <div className="w-full max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-slate-900 mb-1">SimplePaystub – Terms of Service</h1>
        <p className="text-sm text-slate-500">Last updated: April 21, 2026</p>
      </div>

      <div className="bg-white rounded-lg border border-slate-200 p-6 sm:p-8 space-y-8 text-sm text-slate-700 leading-relaxed">
        {/* Intro */}
        <p>
          These Terms of Service (&quot;Terms&quot;) govern your access to and use of the SimplePaystub website,
          applications, and services (collectively, the &quot;Service&quot;). By using the Service, you agree to
          these Terms. If you do not agree, do not use the Service.
        </p>

        <hr className="border-slate-200" />

        {/* 1 */}
        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">1. Eligibility</h2>
          <p>
            You must be at least the age of majority in your jurisdiction to use this Service. By using
            SimplePaystub, you represent that you meet this requirement.
          </p>
        </section>

        <hr className="border-slate-200" />

        {/* 2 */}
        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">2. Description of Service</h2>
          <p>
            SimplePaystub provides tools to generate paystub documents based on information you input. The
            Service may include features such as templates, tax estimation, document storage, and export
            functionality.
          </p>
        </section>

        <hr className="border-slate-200" />

        {/* 3 */}
        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">3. No Warranty</h2>
          <p className="mb-3">
            The Service is provided on an <strong>&quot;as-is&quot; and &quot;as-available&quot;</strong> basis,
            without warranty of any kind, express or implied, including but not limited to warranties of
            merchantability, fitness for a particular purpose, non-infringement, accuracy, availability, or
            uninterrupted access.
          </p>
          <p>We do not guarantee that the Service will be error-free, secure, or continuously available.</p>
        </section>

        <hr className="border-slate-200" />

        {/* 4 */}
        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">4. Tax Calculations Are Estimates Only</h2>
          <p className="mb-3">
            All tax, withholding, and deduction amounts generated by the Service—including Auto Tax and other
            automated calculations—are <strong>estimates only</strong> based on standard tax tables and the
            information you provide.
          </p>
          <p className="mb-2">
            They do not account for your complete financial situation, including but not limited to:
          </p>
          <ul className="list-disc list-inside space-y-1 mb-3 text-slate-600">
            <li>additional income</li>
            <li>credits or deductions</li>
            <li>dependents</li>
            <li>wage-base caps</li>
            <li>year-to-date totals</li>
            <li>local or jurisdiction-specific taxes</li>
          </ul>
          <p className="mb-3">
            Tax laws vary by jurisdiction and change frequently. We do not guarantee compliance with any
            federal, provincial, state, or local regulations.
          </p>
          <p className="mb-3">
            SimplePaystub is <strong>not</strong> a tax preparation service and does not provide tax, legal,
            accounting, or financial advice.
          </p>
          <p>
            You should verify all figures with your employer, a certified tax professional, or the appropriate
            tax authority before relying on any output for filing, employment, lending, or legal purposes.
          </p>
        </section>

        <hr className="border-slate-200" />

        {/* 5 */}
        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">5. Acceptable Use</h2>
          <p className="mb-3">
            You agree to use the Service only for lawful purposes and to create paystubs that accurately
            reflect real income and employment.
          </p>
          <p className="mb-2">You may <strong>not</strong> use the Service to:</p>
          <ul className="list-disc list-inside space-y-1 mb-3 text-slate-600">
            <li>create false, misleading, or fraudulent documents</li>
            <li>misrepresent income or employment to any third party</li>
            <li>engage in unlawful, deceptive, or abusive conduct</li>
          </ul>
          <p className="mb-3">
            This includes (but is not limited to) use involving employers, lenders, landlords, government
            agencies, courts, or insurers.
          </p>
          <p className="mb-3">
            Creating or using false paystubs may violate applicable laws. You are solely responsible for how
            you use any document generated.
          </p>
          <p>
            We reserve the right to suspend or terminate access to the Service at any time if we believe you
            have violated these Terms.
          </p>
        </section>

        <hr className="border-slate-200" />

        {/* 6 */}
        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">6. User Responsibilities</h2>
          <p className="mb-2">You are responsible for:</p>
          <ul className="list-disc list-inside space-y-1 mb-3 text-slate-600">
            <li>the accuracy of all information you provide</li>
            <li>verifying any generated documents before use</li>
            <li>ensuring your use of the Service complies with applicable laws</li>
          </ul>
          <p className="mb-2">
            You agree to <strong>defend, indemnify, and hold harmless</strong> SimplePaystub and its operators
            from any claims, damages, liabilities, losses, and expenses (including legal fees) arising from:
          </p>
          <ul className="list-disc list-inside space-y-1 text-slate-600">
            <li>your use of the Service</li>
            <li>your violation of these Terms</li>
            <li>your misuse of generated documents</li>
          </ul>
        </section>

        <hr className="border-slate-200" />

        {/* 7 */}
        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">7. Accounts</h2>
          <p className="mb-2">If you create an account:</p>
          <ul className="list-disc list-inside space-y-1 mb-3 text-slate-600">
            <li>you are responsible for maintaining the confidentiality of your credentials</li>
            <li>you are responsible for all activity under your account</li>
            <li>you must provide accurate and current information</li>
          </ul>
          <p>
            We may suspend or terminate accounts that are inactive, fraudulent, or in violation of these Terms.
          </p>
        </section>

        <hr className="border-slate-200" />

        {/* 8 */}
        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">8. Payments, Credits, and Subscriptions</h2>
          <p className="mb-2">Certain features of the Service may require payment.</p>
          <ul className="list-disc list-inside space-y-1 mb-3 text-slate-600">
            <li>All fees are displayed at the time of purchase</li>
            <li>Payments are non-refundable unless required by law</li>
            <li>Credits (if applicable) may be subject to expiration or usage limits</li>
            <li>We may change pricing at any time, with reasonable notice</li>
          </ul>
          <p>Failure to pay may result in suspension or termination of access to paid features.</p>
        </section>

        <hr className="border-slate-200" />

        {/* 9 */}
        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">9. Intellectual Property</h2>
          <p className="mb-3">
            All content, software, design, and functionality of the Service are owned by SimplePaystub or its
            licensors and are protected by intellectual property laws.
          </p>
          <p className="mb-2">
            You are granted a limited, non-exclusive, non-transferable license to use the Service for its
            intended purpose. You may not:
          </p>
          <ul className="list-disc list-inside space-y-1 text-slate-600">
            <li>copy, modify, or distribute the Service</li>
            <li>reverse engineer or attempt to extract source code</li>
            <li>use the Service for unauthorized commercial purposes</li>
          </ul>
        </section>

        <hr className="border-slate-200" />

        {/* 10 */}
        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">10. Data and Privacy</h2>
          <p className="mb-3">
            Your use of the Service is also governed by our{' '}
            <Link href={paths.privacy} className="text-primary hover:underline">
              Privacy Policy
            </Link>
            .
          </p>
          <p>
            You are responsible for ensuring that any personal data you input into the Service is handled in
            compliance with applicable privacy laws.
          </p>
        </section>

        <hr className="border-slate-200" />

        {/* 11 */}
        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">11. Limitation of Liability</h2>
          <p className="mb-3">
            To the fullest extent permitted by law, SimplePaystub and its operators shall not be liable for
            any indirect, incidental, consequential, special, or punitive damages, including but not limited
            to:
          </p>
          <ul className="list-disc list-inside space-y-1 mb-3 text-slate-600">
            <li>incorrect tax calculations</li>
            <li>missed withholdings</li>
            <li>misreported income</li>
            <li>penalties, fines, or interest</li>
            <li>loss resulting from reliance on generated documents</li>
          </ul>
          <p className="mb-3">
            Our total liability for any claim related to the Service shall not exceed the amount you paid us
            in the twelve (12) months preceding the claim.
          </p>
          <p>
            Some jurisdictions do not allow the exclusion or limitation of certain damages, so some of the
            above limitations may not apply to you.
          </p>
        </section>

        <hr className="border-slate-200" />

        {/* 12 */}
        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">12. Termination</h2>
          <p className="mb-3">
            We may suspend or terminate your access to the Service at any time, with or without notice, for
            any reason, including violation of these Terms.
          </p>
          <p>You may stop using the Service at any time.</p>
        </section>

        <hr className="border-slate-200" />

        {/* 13 */}
        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">13. Changes to the Service</h2>
          <p>
            We may modify, suspend, or discontinue any part of the Service at any time without liability.
          </p>
        </section>

        <hr className="border-slate-200" />

        {/* 14 */}
        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">14. Updates to Terms</h2>
          <p className="mb-3">
            We may update these Terms from time to time. For material changes, we will provide notice (such
            as via email or within the Service).
          </p>
          <p>
            Your continued use of the Service after changes become effective constitutes acceptance of the
            revised Terms.
          </p>
        </section>

        <hr className="border-slate-200" />

        {/* 15 */}
        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">15. Governing Law</h2>
          <p>
            These Terms are governed by the laws of the Province of Ontario and the laws of Canada applicable
            therein, without regard to conflict of law principles.
          </p>
        </section>

        <hr className="border-slate-200" />

        {/* 16 */}
        <section>
          <h2 className="text-base font-semibold text-slate-900 mb-2">16. Contact</h2>
          <p className="mb-2">
            If you have any questions about these Terms, you may contact us at:
          </p>
          <p>
            <strong>Email:</strong>{' '}
            <a href="mailto:support@simplepaystub.com" className="text-primary hover:underline">
              support@simplepaystub.com
            </a>
          </p>
        </section>

        <hr className="border-slate-200" />

        <p className="text-slate-500 italic">
          By using SimplePaystub, you acknowledge that you have read, understood, and agree to these Terms.
        </p>
      </div>
    </div>
  );
}
