export const LOADING_STATES = {
  DOWNLOADING: 'DOWNLOADING',
  SENDING_EMAIL: 'SENDING_EMAIL'
}
export const PROVINCES = [
  { name: 'Alberta', abbreviation: 'AB' },
  { name: 'British Columbia', abbreviation: 'BC' },
  { name: 'Manitoba', abbreviation: 'MB' },
  { name: 'New Brunswick', abbreviation: 'NB' },
  { name: 'Newfoundland and Labrador', abbreviation: 'NL' },
  { name: 'Nova Scotia', abbreviation: 'NS' },
  { name: 'Ontario', abbreviation: 'ON' },
  { name: 'Prince Edward Island', abbreviation: 'PE' },
  { name: 'Quebec', abbreviation: 'QC' },
  { name: 'Saskatchewan', abbreviation: 'SK' },
  { name: 'Northwest Territories', abbreviation: 'NT' },
  { name: 'Nunavut', abbreviation: 'NU' },
  { name: 'Yukon', abbreviation: 'YT' },
];

export const US_STATES = [
  { name: 'Alabama', abbreviation: 'AL' },
  { name: 'Alaska', abbreviation: 'AK' },
  { name: 'Arizona', abbreviation: 'AZ' },
  { name: 'Arkansas', abbreviation: 'AR' },
  { name: 'California', abbreviation: 'CA' },
  { name: 'Colorado', abbreviation: 'CO' },
  { name: 'Connecticut', abbreviation: 'CT' },
  { name: 'Delaware', abbreviation: 'DE' },
  { name: 'Florida', abbreviation: 'FL' },
  { name: 'Georgia', abbreviation: 'GA' },
  { name: 'Hawaii', abbreviation: 'HI' },
  { name: 'Idaho', abbreviation: 'ID' },
  { name: 'Illinois', abbreviation: 'IL' },
  { name: 'Indiana', abbreviation: 'IN' },
  { name: 'Iowa', abbreviation: 'IA' },
  { name: 'Kansas', abbreviation: 'KS' },
  { name: 'Kentucky', abbreviation: 'KY' },
  { name: 'Louisiana', abbreviation: 'LA' },
  { name: 'Maine', abbreviation: 'ME' },
  { name: 'Maryland', abbreviation: 'MD' },
  { name: 'Massachusetts', abbreviation: 'MA' },
  { name: 'Michigan', abbreviation: 'MI' },
  { name: 'Minnesota', abbreviation: 'MN' },
  { name: 'Mississippi', abbreviation: 'MS' },
  { name: 'Missouri', abbreviation: 'MO' },
  { name: 'Montana', abbreviation: 'MT' },
  { name: 'Nebraska', abbreviation: 'NE' },
  { name: 'Nevada', abbreviation: 'NV' },
  { name: 'New Hampshire', abbreviation: 'NH' },
  { name: 'New Jersey', abbreviation: 'NJ' },
  { name: 'New Mexico', abbreviation: 'NM' },
  { name: 'New York', abbreviation: 'NY' },
  { name: 'North Carolina', abbreviation: 'NC' },
  { name: 'North Dakota', abbreviation: 'ND' },
  { name: 'Ohio', abbreviation: 'OH' },
  { name: 'Oklahoma', abbreviation: 'OK' },
  { name: 'Oregon', abbreviation: 'OR' },
  { name: 'Pennsylvania', abbreviation: 'PA' },
  { name: 'Rhode Island', abbreviation: 'RI' },
  { name: 'South Carolina', abbreviation: 'SC' },
  { name: 'South Dakota', abbreviation: 'SD' },
  { name: 'Tennessee', abbreviation: 'TN' },
  { name: 'Texas', abbreviation: 'TX' },
  { name: 'Utah', abbreviation: 'UT' },
  { name: 'Vermont', abbreviation: 'VT' },
  { name: 'Virginia', abbreviation: 'VA' },
  { name: 'Washington', abbreviation: 'WA' },
  { name: 'West Virginia', abbreviation: 'WV' },
  { name: 'Wisconsin', abbreviation: 'WI' },
  { name: 'Wyoming', abbreviation: 'WY' },
  { name: 'District of Columbia', abbreviation: 'DC' },
];

export const DEFAULT_PAYMENT_FREQUENCY = 'Bi-weekly';
export const PAYMENT_FREQUENCIES = [
  'Daily',
  'Weekly',
  'Bi-weekly',
  'Semi-monthly',
  'Monthly',
  'Quarterly',
  'Semi-annually',
  'Annually',
];

export const DEFAULT_PAYMENT_TYPE = 'Hourly';
export const PAYMENT_TYPE = ['Hourly', 'Salary'];
export const DEFAULT_TEMPLATE = 'NOVA' as const;

const PAYER_DEFAULT_VALUES = {
  logo: '',
  name: '',
  address: '',
  addressSecond: '',
  city: '',
  stateOrProvince: '',
  zipOrPostalCode: '',
  countryOrRegion: '',
  phoneNumber: '',
  extNo: '',
  email: '',
};

const PAYEE_DEFAULT_VALUES = {
  name: '',
  address: '',
  addressSecond: '',
  city: '',
  stateOrProvince: '',
  zipOrPostalCode: '',
  countryOrRegion: '',
  phoneNumber: '',
  extNo: '',
  email: '',
};

const PAYMENT_DEFAULT_VALUES = {
  name: 'Regular Salary',
  type: DEFAULT_PAYMENT_TYPE,
  hourlyRate: '',
  annualSalary: '',
  numOfHours: '',
  date: new Date(),
  periodStart: new Date(),
  periodEnd: new Date(),
  frequency: '',
  chequeNumber: '',
  ytd: '',
};

export const PAY_STUB_FORM_DEFAULT_VALUES = {
  payer: PAYER_DEFAULT_VALUES,
  payee: PAYEE_DEFAULT_VALUES,
  payment: PAYMENT_DEFAULT_VALUES,
  deductions: [],
  benefits: [],
  template: DEFAULT_TEMPLATE,
};

export const COUNTRIES = [
  { name: 'United States', slug: 'US' },
  { name: 'Canada', slug: 'CA' },
  { name: 'Afghanistan', slug: 'AF' },
  { name: 'Åland Islands', slug: 'AX' },
  { name: 'Albania', slug: 'AL' },
  { name: 'Algeria', slug: 'DZ' },
  { name: 'American Samoa', slug: 'AS' },
  { name: 'Andorra', slug: 'AD' },
  { name: 'Angola', slug: 'AO' },
  { name: 'Anguilla', slug: 'AI' },
  { name: 'Antarctica', slug: 'AQ' },
  { name: 'Antigua and Barbuda', slug: 'AG' },
  { name: 'Argentina', slug: 'AR' },
  { name: 'Armenia', slug: 'AM' },
  { name: 'Aruba', slug: 'AW' },
  { name: 'Australia', slug: 'AU' },
  { name: 'Austria', slug: 'AT' },
  { name: 'Azerbaijan', slug: 'AZ' },
  { name: 'Bahamas', slug: 'BS' },
  { name: 'Bahrain', slug: 'BH' },
  { name: 'Bangladesh', slug: 'BD' },
  { name: 'Barbados', slug: 'BB' },
  { name: 'Belarus', slug: 'BY' },
  { name: 'Belgium', slug: 'BE' },
  { name: 'Belize', slug: 'BZ' },
  { name: 'Benin', slug: 'BJ' },
  { name: 'Bermuda', slug: 'BM' },
  { name: 'Bhutan', slug: 'BT' },
  { name: 'Bolivia', slug: 'BO' },
  { name: 'Bonaire, Sint Eustatius and Saba', slug: 'BQ' },
  { name: 'Bosnia and Herzegovina', slug: 'BA' },
  { name: 'Botswana', slug: 'BW' },
  { name: 'Bouvet Island', slug: 'BV' },
  { name: 'Brazil', slug: 'BR' },
  { name: 'British Indian Ocean Territory', slug: 'IO' },
  { name: 'Brunei Darussalam', slug: 'BN' },
  { name: 'Bulgaria', slug: 'BG' },
  { name: 'Burkina Faso', slug: 'BF' },
  { name: 'Burundi', slug: 'BI' },
  { name: 'Cambodia', slug: 'KH' },
  { name: 'Cameroon', slug: 'CM' },
  { name: 'Cape Verde', slug: 'CV' },
  { name: 'Cayman Islands', slug: 'KY' },
  { name: 'Central African Republic', slug: 'CF' },
  { name: 'Chad', slug: 'TD' },
  { name: 'Chile', slug: 'CL' },
  { name: 'China', slug: 'CN' },
  { name: 'Christmas Island', slug: 'CX' },
  { name: 'Cocos (Keeling) Islands', slug: 'CC' },
  { name: 'Colombia', slug: 'CO' },
  { name: 'Comoros', slug: 'KM' },
  { name: 'Congo, Republic of the (Brazzaville)', slug: 'CG' },
  { name: 'Congo, the Democratic Republic of the (Kinshasa)', slug: 'CD' },
  { name: 'Cook Islands', slug: 'CK' },
  { name: 'Costa Rica', slug: 'CR' },
  { name: "Côte d'Ivoire, Republic of", slug: 'CI' },
  { name: 'Croatia', slug: 'HR' },
  { name: 'Cuba', slug: 'CU' },
  { name: 'Curaçao', slug: 'CW' },
  { name: 'Cyprus', slug: 'CY' },
  { name: 'Czech Republic', slug: 'CZ' },
  { name: 'Denmark', slug: 'DK' },
  { name: 'Djibouti', slug: 'DJ' },
  { name: 'Dominica', slug: 'DM' },
  { name: 'Dominican Republic', slug: 'DO' },
  { name: 'Ecuador', slug: 'EC' },
  { name: 'Egypt', slug: 'EG' },
  { name: 'El Salvador', slug: 'SV' },
  { name: 'Equatorial Guinea', slug: 'GQ' },
  { name: 'Eritrea', slug: 'ER' },
  { name: 'Estonia', slug: 'EE' },
  { name: 'Ethiopia', slug: 'ET' },
  { name: 'Falkland Islands (Islas Malvinas)', slug: 'FK' },
  { name: 'Faroe Islands', slug: 'FO' },
  { name: 'Fiji', slug: 'FJ' },
  { name: 'Finland', slug: 'FI' },
  { name: 'France', slug: 'FR' },
  { name: 'French Guiana', slug: 'GF' },
  { name: 'French Polynesia', slug: 'PF' },
  { name: 'French Southern and Antarctic Lands', slug: 'TF' },
  { name: 'Gabon', slug: 'GA' },
  { name: 'Gambia, The', slug: 'GM' },
  { name: 'Georgia', slug: 'GE' },
  { name: 'Germany', slug: 'DE' },
  { name: 'Ghana', slug: 'GH' },
  { name: 'Gibraltar', slug: 'GI' },
  { name: 'Greece', slug: 'GR' },
  { name: 'Greenland', slug: 'GL' },
  { name: 'Grenada', slug: 'GD' },
  { name: 'Guadeloupe', slug: 'GP' },
  { name: 'Guam', slug: 'GU' },
  { name: 'Guatemala', slug: 'GT' },
  { name: 'Guernsey', slug: 'GG' },
  { name: 'Guinea', slug: 'GN' },
  { name: 'Guinea-Bissau', slug: 'GW' },
  { name: 'Guyana', slug: 'GY' },
  { name: 'Haiti', slug: 'HT' },
  { name: 'Heard Island and McDonald Islands', slug: 'HM' },
  { name: 'Holy See (Vatican City)', slug: 'VA' },
  { name: 'Honduras', slug: 'HN' },
  { name: 'Hong Kong', slug: 'HK' },
  { name: 'Hungary', slug: 'HU' },
  { name: 'Iceland', slug: 'IS' },
  { name: 'India', slug: 'IN' },
  { name: 'Indonesia', slug: 'ID' },
  { name: 'Iran, Islamic Republic of', slug: 'IR' },
  { name: 'Iraq', slug: 'IQ' },
  { name: 'Ireland', slug: 'IE' },
  { name: 'Isle of Man', slug: 'IM' },
  { name: 'Israel', slug: 'IL' },
  { name: 'Italy', slug: 'IT' },
  { name: 'Jamaica', slug: 'JM' },
  { name: 'Japan', slug: 'JP' },
  { name: 'Jersey', slug: 'JE' },
  { name: 'Jordan', slug: 'JO' },
  { name: 'Kazakhstan', slug: 'KZ' },
  { name: 'Kenya', slug: 'KE' },
  { name: 'Kiribati', slug: 'KI' },
  { name: "Korea, Democratic People's Republic of", slug: 'KP' },
  { name: 'Korea, Republic of', slug: 'KR' },
  { name: 'Kosovo', slug: 'XK' },
  { name: 'Kuwait', slug: 'KW' },
  { name: 'Kyrgyzstan', slug: 'KG' },
  { name: 'Laos', slug: 'LA' },
  { name: 'Latvia', slug: 'LV' },
  { name: 'Lebanon', slug: 'LB' },
  { name: 'Lesotho', slug: 'LS' },
  { name: 'Liberia', slug: 'LR' },
  { name: 'Libya', slug: 'LY' },
  { name: 'Liechtenstein', slug: 'LI' },
  { name: 'Lithuania', slug: 'LT' },
  { name: 'Luxembourg', slug: 'LU' },
  { name: 'Macao', slug: 'MO' },
  { name: 'Macedonia, Republic of', slug: 'MK' },
  { name: 'Madagascar', slug: 'MG' },
  { name: 'Malawi', slug: 'MW' },
  { name: 'Malaysia', slug: 'MY' },
  { name: 'Maldives', slug: 'MV' },
  { name: 'Mali', slug: 'ML' },
  { name: 'Malta', slug: 'MT' },
  { name: 'Marshall Islands', slug: 'MH' },
  { name: 'Martinique', slug: 'MQ' },
  { name: 'Mauritania', slug: 'MR' },
  { name: 'Mauritius', slug: 'MU' },
  { name: 'Mayotte', slug: 'YT' },
  { name: 'Mexico', slug: 'MX' },
  { name: 'Micronesia, Federated States of', slug: 'FM' },
  { name: 'Moldova', slug: 'MD' },
  { name: 'Monaco', slug: 'MC' },
  { name: 'Mongolia', slug: 'MN' },
  { name: 'Montenegro', slug: 'ME' },
  { name: 'Montserrat', slug: 'MS' },
  { name: 'Morocco', slug: 'MA' },
  { name: 'Mozambique', slug: 'MZ' },
  { name: 'Myanmar', slug: 'MM' },
  { name: 'Namibia', slug: 'NA' },
  { name: 'Nauru', slug: 'NR' },
  { name: 'Nepal', slug: 'NP' },
  { name: 'Netherlands', slug: 'NL' },
  { name: 'New Caledonia', slug: 'NC' },
  { name: 'New Zealand', slug: 'NZ' },
  { name: 'Nicaragua', slug: 'NI' },
  { name: 'Niger', slug: 'NE' },
  { name: 'Nigeria', slug: 'NG' },
  { name: 'Niue', slug: 'NU' },
  { name: 'Norfolk Island', slug: 'NF' },
  { name: 'Northern Mariana Islands', slug: 'MP' },
  { name: 'Norway', slug: 'NO' },
  { name: 'Oman', slug: 'OM' },
  { name: 'Pakistan', slug: 'PK' },
  { name: 'Palau', slug: 'PW' },
  { name: 'Palestine', slug: 'PS' },
  { name: 'Panama', slug: 'PA' },
  { name: 'Papua New Guinea', slug: 'PG' },
  { name: 'Paraguay', slug: 'PY' },
  { name: 'Peru', slug: 'PE' },
  { name: 'Philippines', slug: 'PH' },
  { name: 'Pitcairn', slug: 'PN' },
  { name: 'Poland', slug: 'PL' },
  { name: 'Portugal', slug: 'PT' },
  { name: 'Puerto Rico', slug: 'PR' },
  { name: 'Qatar', slug: 'QA' },
  { name: 'Réunion', slug: 'RE' },
  { name: 'Romania', slug: 'RO' },
  { name: 'Russian Federation', slug: 'RU' },
  { name: 'Rwanda', slug: 'RW' },
  { name: 'Saint Barthélemy', slug: 'BL' },
  { name: 'Saint Helena, Ascension and Tristan da Cunha', slug: 'SH' },
  { name: 'Saint Kitts and Nevis', slug: 'KN' },
  { name: 'Saint Lucia', slug: 'LC' },
  { name: 'Saint Martin', slug: 'MF' },
  { name: 'Saint Pierre and Miquelon', slug: 'PM' },
  { name: 'Saint Vincent and the Grenadines', slug: 'VC' },
  { name: 'Samoa', slug: 'WS' },
  { name: 'San Marino', slug: 'SM' },
  { name: 'Sao Tome and Principe', slug: 'ST' },
  { name: 'Saudi Arabia', slug: 'SA' },
  { name: 'Senegal', slug: 'SN' },
  { name: 'Serbia', slug: 'RS' },
  { name: 'Seychelles', slug: 'SC' },
  { name: 'Sierra Leone', slug: 'SL' },
  { name: 'Singapore', slug: 'SG' },
  { name: 'Sint Maarten (Dutch part)', slug: 'SX' },
  { name: 'Slovakia', slug: 'SK' },
  { name: 'Slovenia', slug: 'SI' },
  { name: 'Solomon Islands', slug: 'SB' },
  { name: 'Somalia', slug: 'SO' },
  { name: 'South Africa', slug: 'ZA' },
  { name: 'South Georgia and South Sandwich Islands', slug: 'GS' },
  { name: 'South Sudan', slug: 'SS' },
  { name: 'Spain', slug: 'ES' },
  { name: 'Sri Lanka', slug: 'LK' },
  { name: 'Sudan', slug: 'SD' },
  { name: 'Suriname', slug: 'SR' },
  { name: 'Eswatini', slug: 'SZ' },
  { name: 'Sweden', slug: 'SE' },
  { name: 'Switzerland', slug: 'CH' },
  { name: 'Syrian Arab Republic', slug: 'SY' },
  { name: 'Taiwan', slug: 'TW' },
  { name: 'Tajikistan', slug: 'TJ' },
  { name: 'Tanzania, United Republic of', slug: 'TZ' },
  { name: 'Thailand', slug: 'TH' },
  { name: 'Timor-Leste', slug: 'TL' },
  { name: 'Togo', slug: 'TG' },
  { name: 'Tokelau', slug: 'TK' },
  { name: 'Tonga', slug: 'TO' },
  { name: 'Trinidad and Tobago', slug: 'TT' },
  { name: 'Tunisia', slug: 'TN' },
  { name: 'Turkey', slug: 'TR' },
  { name: 'Turkmenistan', slug: 'TM' },
  { name: 'Turks and Caicos Islands', slug: 'TC' },
  { name: 'Tuvalu', slug: 'TV' },
  { name: 'Uganda', slug: 'UG' },
  { name: 'Ukraine', slug: 'UA' },
  { name: 'United Arab Emirates', slug: 'AE' },
  { name: 'United Kingdom', slug: 'GB' },
  { name: 'United States Minor Outlying Islands', slug: 'UM' },
  { name: 'Uruguay', slug: 'UY' },
  { name: 'Uzbekistan', slug: 'UZ' },
  { name: 'Vanuatu', slug: 'VU' },
  { name: 'Venezuela, Bolivarian Republic of', slug: 'VE' },
  { name: 'Vietnam', slug: 'VN' },
  { name: 'Virgin Islands, British', slug: 'VG' },
  { name: 'Virgin Islands, U.S.', slug: 'VI' },
  { name: 'Wallis and Futuna', slug: 'WF' },
  { name: 'Western Sahara', slug: 'EH' },
  { name: 'Yemen', slug: 'YE' },
  { name: 'Zambia', slug: 'ZM' },
  { name: 'Zimbabwe', slug: 'ZW' },
];
